### ISSUE TITLE
REGEXP '^[-]?[0-9]+$'  fails on int64 column.

### ISSUE THREAD

**Issue by joel-rieke** [dolthub/go-mysql-server#1055]
I know this sounds crazy to run a regex on a BIGINT column, however, when I do so in mysql, it works fine.  Notice this regex will match every number in a BIGINT, so kind of pointless.  However, running this regex against a BIGINT in go-mysql-server returns no matches.

Another regex that works in mysql to return a result:
'^[-]?2[0-9]+$' 

But on go-mysql-server, no results for the same dataset.

In the interest of compatibility with mysql, perhaps it would be nice to support REGEX on int64 columns?

**Comment by timsehn** [comment]
Goal is 100% MySQL compatibility. Thanks for the bug report. We'll get on it.

**Comment by bpf120** [comment]
Hi @joel-rieke, thanks for the report. We'd love to learn about your use case too. Feel free to share here, email me(brianf@dolthub.com), or come by our Discord.

https://discord.com/invite/RFwfYpu

**Comment by fulghum** [comment]
Thanks for reporting this one @joel-rieke ! The fix was merged in on Friday and released in Dolt 0.40.9. Please let us know if you find any other issues.

**Comment by joel-rieke** [comment]
Tested the change in our project and it fixes the problem we were having.  Thanks for looking into this!
