### ISSUE TITLE
I proxies mysql-8.0.23 to go-mysql-server,some problem confuse me

### ISSUE THREAD

**Issue by RyanCode** [dolthub/go-mysql-server#1089]
>I proxies mysql-8.0.23 to go-mysql-server,cmd mysql client can not connect to go-mysql-server,but navicat can,why?
```html
time="2022-06-30T16:19:44+08:00" level=info msg=NewConnection DisableClientMultiStatements=false connectionID=4
time="2022-06-30T16:19:44+08:00" level=warning msg="from client :&{{!\x00\x00\x00\x03select @@version_comment limit 1} select @@version_comment limit 1}"
time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x01\x00\x00\x01\x01"
time="2022-06-30T16:19:44+08:00" level=warning msg="from server: '\x00\x00\x02\x03def\x00\x00\x00\x11@@version_comment\x00\f!\x00\xff\xff\x00\x00\xfd\x00\x00\x1f\x00\x00"
time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x05\x00\x00\x03\xfe\x00\x00\x02\x00"
time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x1d\x00\x00\x04\x1cMySQL Community Server - GPL"
time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x05\x00\x00\x05\xfe\x00\x00\x02\x00"
time="2022-06-30T16:19:48+08:00" level=warning msg="from client :&{{\x0f\x00\x00\x00\x03show databases} show databases}"
time="2022-06-30T16:19:48+08:00" level=warning msg="from client :%!s(<nil>)"
time="2022-06-30T16:19:48+08:00" level=error msg="failed to set the database EOF"
time="2022-06-30T16:19:48+08:00" level=warning msg="from server: \x01\x00\x00\x01\x01"
time="2022-06-30T16:19:48+08:00" level=warning msg="from server: .\x00\x00\x02\x03def\x00\bSCHEMATA\x00\bDatabase\bDatabase\f!\x00\xc0\x00\x00\x00\xfd\x00\x00\x00\x00\x00"
time="2022-06-30T16:19:48+08:00" level=error msg="Failed to write client packet."
```

**Comment by RyanCode** [comment]
> > I proxies mysql-8.0.23 to go-mysql-server,cmd mysql client can not connect to go-mysql-server,but navicat can,why?
> 
> ```
> time="2022-06-30T16:19:44+08:00" level=info msg=NewConnection DisableClientMultiStatements=false connectionID=4
> time="2022-06-30T16:19:44+08:00" level=warning msg="from client :&{{!\x00\x00\x00\x03select @@version_comment limit 1} select @@version_comment limit 1}"
> time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x01\x00\x00\x01\x01"
> time="2022-06-30T16:19:44+08:00" level=warning msg="from server: '\x00\x00\x02\x03def\x00\x00\x00\x11@@version_comment\x00\f!\x00\xff\xff\x00\x00\xfd\x00\x00\x1f\x00\x00"
> time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x05\x00\x00\x03\xfe\x00\x00\x02\x00"
> time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x1d\x00\x00\x04\x1cMySQL Community Server - GPL"
> time="2022-06-30T16:19:44+08:00" level=warning msg="from server: \x05\x00\x00\x05\xfe\x00\x00\x02\x00"
> time="2022-06-30T16:19:48+08:00" level=warning msg="from client :&{{\x0f\x00\x00\x00\x03show databases} show databases}"
> time="2022-06-30T16:19:48+08:00" level=warning msg="from client :%!s(<nil>)"
> time="2022-06-30T16:19:48+08:00" level=error msg="failed to set the database EOF"
> time="2022-06-30T16:19:48+08:00" level=warning msg="from server: \x01\x00\x00\x01\x01"
> time="2022-06-30T16:19:48+08:00" level=warning msg="from server: .\x00\x00\x02\x03def\x00\bSCHEMATA\x00\bDatabase\bDatabase\f!\x00\xc0\x00\x00\x00\xfd\x00\x00\x00\x00\x00"
> time="2022-06-30T16:19:48+08:00" level=error msg="Failed to write client packet."
> ```

**Comment by fulghum** [comment]
Hey @RyanCode, looks like you got this figured out. Feel free to share the issue resolution here if you can – it could help others. 

Hope you're having a good experience with go-mysql-server. Let us know if you hit any other issues or snags and we're happy to help. We also always love to hear what customers are doing with the package.
