### ISSUE TITLE
go 1.17 support

### ISSUE THREAD

**Issue by joel-rieke** [dolthub/go-mysql-server#1096]
Any possibility of supporting go 1.17?  We still use go 1.17 for now, we don't have plans to move to 1.18 due to the additional compilation costs.  Also,we are not using 1.18 features.

**Comment by linkerlin** [comment]
> Any possibility of supporting go 1.17? We still use go 1.17 for now, we don't have plans to move to 1.18 due to the additional compilation costs. Also,we are not using 1.18 features.

If you are using go, the cost of upgrading go's version is a tex for using it.

**Comment by joel-rieke** [comment]
> > Any possibility of supporting go 1.17? We still use go 1.17 for now, we don't have plans to move to 1.18 due to the additional compilation costs. Also,we are not using 1.18 features.
> 
> If you are using go, the cost of upgrading go's version is a tex for using it.

? a tex?

**Comment by fulghum** [comment]
Hey @joel-rieke, sorry for the slow response. We'd prefer to stick to go 1.18 and stay up to date with the latest release. We'd be happy to discuss it internally if this is an issue for other customers, too, though. I haven't personally noticed a huge hit from compile times in 1.18, but I have read the issue on it over in the golang repo. 

In the meantime, do you all have a good workaround? Have you already built a script to downgrade the `go.mod` file before you build go-mysql-server?

**Comment by joel-rieke** [comment]
I forked back just prior to this change and have been working off the fork ever since.  :(  I'd rather not have to do this.  I think there are still pretty strong feelings by many developers about 1.18.  It seems to me they ought to be able to detect whether the new 1.18 features are being used in a code base and if not, don't pay the extra cost that 1.18 requires in compilation, but so far I'm not seeing any optimizations in this direction.  Seems like a big energy waste to me.

**Comment by fulghum** [comment]
Have you all had a chance to try out the Go 1.19 release that just came out this week to see if it helps your compilation times? 

Now that 1.19 is out, that means 1.19 and 1.18 are the only officially supported Go versions, so switching back to 1.17 really won't be an option for us. We still care about how this affects your team though, and want to hear if there's anything else we can do, but we won't be able to revert to 1.17.

**Comment by fulghum** [comment]
Haven't heard back on this issue in about a month, so closing this one out now that 1.19 and 1.18 are the official TLS golang versions.
