### ISSUE TITLE
Is it possible to run raw sql queries to mock the database?

### ISSUE THREAD

**Issue by arthurl311** [dolthub/go-mysql-server#1144]
I'm thinking in running a raw sql query to mock my database instead of creating a struct schema.

Example:
I run this query and it creates the table `address` in-memory
 
` CREATE TABLE address (id INT PRIMARY KEY);
`

Is it possible or I need to define the schema?

**Comment by VinaiRachakonda** [comment]
Yes it is possible. You can work backwards from our testing setup starting [here](https://github.com/dolthub/go-mysql-server/blob/main/enginetest/evaluation.go#L255). 

Essentially, you will have to define query engine, which we have some default initializations of in our testing environment. Please feel free to follow up if you have any additional questions.
