### ISSUE TITLE
How can i change the log level?

### ISSUE THREAD

**Issue by arthurl311** [dolthub/go-mysql-server#1219]
How can i manipulate the log level from my tests?

![image](https://user-images.githubusercontent.com/101644397/186916032-33fd597f-045d-479c-8d52-baeb49ba9387.png)

Example: change info level to debug level

**Comment by fulghum** [comment]
Hey @arthurl311, thanks for checking out the go-mysql-server project. You can use `github.com/sirupsen/logrus` to set the log level, like this: 
```
	logrus.SetLevel(logrus.TraceLevel)
```

Give that a shot and let us know if it doesn't work for you.

**Comment by arthurl311** [comment]
Worked, Thanks :)
