### ISSUE TITLE
Cannot connect to database to query MemoryTable

### ISSUE THREAD

**Issue by osawyerr** [dolthub/go-mysql-server#1314]
Hi there.

Following the example code here - https://github.com/dolthub/go-mysql-server/blob/main/_example/main.go 

I can't connect to the server to query a MemoryTable using the command below. The error is also shown
```
mysql --host=127.0.0.1 --port=3306 -u root mydb -e "SELECT * FROM mytable"
ERROR 1045 (28000): User not found 'root'
```

There doesn't seem to be an obvious way to configure users.

**Comment by timsehn** [comment]
As discussed on Discord, @Hydrocharged is going to check this out when he wakes up and see if we broke it in our permissions changes.

**Comment by Hydrocharged** [comment]
The README was out of date and no longer relevant to the current GMS. The README has been updated to reflect current usage.
