### ISSUE TITLE
README Rewrite

### ISSUE THREAD

**Issue by timsehn** [dolthub/go-mysql-server#1317]
The current README has not changed substantially since we took over this project three years ago. We should rewrite the README to reflect the current state of the project.

**Comment by JCOR11599** [comment]
There's a script Zach made me write a while back that somewhat updates the README (just the function sql counts)
https://github.com/dolthub/go-mysql-server/blob/main/scripts/generate_readme.go

**Comment by timsehn** [comment]
@zachmu did this.
