### ISSUE TITLE
Hangs on TPC-H Query 1

### ISSUE THREAD

**Issue by osawyerr** [dolthub/go-mysql-server#1340]
Hi there,

[go-mysql-server](https://github.com/dolthub/go-mysql-server) hangs when running _TPC-H Query 1_. 

We loaded TPC-H data (scale factor 50) into our custom storage layer and integrated with go-mysql-server as the SQL Query Engine. Running TPC-H Query 1 which scans approx 300M rows split evenly in about 3000 partitions, the query hangs once all partitions have been queried and never returns. We do filter pushdown but its filtering effect on this TPCH Query 1 is minimal.
 
```
select
    l_returnflag,
    l_linestatus,
    sum(l_quantity) as sum_qty,
    sum(l_extendedprice) as sum_base_price,
    sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
    sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
    avg(l_quantity) as avg_qty,
    avg(l_extendedprice) as avg_price,
    avg(l_discount) as avg_disc,
    count(*) as count_order
from
    lineitem
where
    l_shipdate <= date '1998-12-01' - interval '70 day'
group by
    l_returnflag,
    l_linestatus
order by
    l_returnflag,
    l_linestatus;
```

Table is the standard _lineitem_ table from TPC-H. Definition below:
```
create table lineitem
(
    l_orderkey      integer        not null,
    l_partkey       integer        not null,
    l_suppkey       integer        not null,
    l_linenumber    integer        not null,
    l_quantity      numeric(15, 2) not null,
    l_extendedprice numeric(15, 2) not null,
    l_discount      numeric(15, 2) not null,
    l_tax           numeric(15, 2) not null,
    l_returnflag    char           not null,
    l_linestatus    char           not null,
    l_shipdate      date           not null,
    l_commitdate    date           not null,
    l_receiptdate   date           not null,
    l_shipinstruct  char(25)       not null,
    l_shipmode      char(10)       not null,
    l_comment       varchar(44)    not null
);
```

We've ruled out our underlying storage layer as the cause of the problem. It performs well when we use another SQL Query Engine. The query is successful (and pretty quick), however when using go-mysql-server the query hangs forever. 

You can probably reproduce this by loading TPC-H Scale factor 50 data into _dolt_ and running this TPC-H Query 1 (300M rows in lineitem table).

**Comment by zachmu** [comment]
Thanks for the report.

Can you try running your server with `GOMAXPROCS=1`? If it succeeds with that configuration, that's an indication that parallel table access is the issue -- table partitions are scanned in parallel by default, but this is disabled when `GOMAXPROCS=1`.

Can you give us a link to your backend implementation?
