### ISSUE TITLE
regex-metrics can't be initialized

### ISSUE THREAD

**Issue by Merovius** [dolthub/go-mysql-server#146]
According to the README, we should set some global variables to collect metrics. Unfortunately, the `regex` package is internal, so it's not possible for users to set those variables.

In general, I really feel that the ergonomics of using metrics should be improved. Copy-pasting from the README is hardly a good workflow, not least because we have to manually poll the README to see if new metrics where added or old ones changed. The global variables containing the counters are not documented in regards to what labels they expect. And of course, counter-variables should not be global anyway, but fields of the corresponding struct.

IMO a preferable API would be a `RegisterMetrics` method on `sqle.Engine` and the like, which takes a [provider.Provider](https://godoc.org/github.com/go-kit/kit/metrics/provider#Provider), or - even better - taking a `Provider` in the constructors. That way, the user does not have to set up the specific metrics used with the correct fields and we can use our own provider that registers the metrics to a custom `prometheus.Registry`.

**Comment by zachmu** [comment]
Hi Axel,

Yes, I agree that metrics need quite a bit of work. We are currently prioritizing correctness of the engine before proceeding to this kind of performance / analysis concern, so it will be some time before we address this. Would you be willing to contribute a PR implementing what you're describing?

Zach
