### ISSUE TITLE
`convert_tz` is not working as expected with `@@GLOBAL.time_zone`

### ISSUE THREAD

**Issue by sananguliyev** [dolthub/go-mysql-server#1533]
When I run `select convert_tz(now(), @@GLOBAL.time_zone, '+00:00');` I get `null` instead of some date time.

**Comment by fulghum** [comment]
Hey @sananguliyev, thanks for checking out `go-mysql-server` and for taking the time to report this. 

It looks like [our tests for `convert_tz()`](https://github.com/dolthub/go-mysql-server/blob/f1bc6b807027ab15f7ef09c69c064a707d47de00/sql/expression/function/convert_tz_test.go) don't cover the default value, `SYSTEM`. I suspect this is the issue. Just to double-check... could you confirm that `@@GLOBAL.time_zone` is set to the default value, `SYSTEM` in your environment? 

_(Not specific to GMS, but a note for our team... [Dolt documentation also needs to be updated ](https://docs.dolthub.com/sql-reference/sql-support/expressions-functions-operators#functions-and-operators) to mark `convert_tz` as supported)_

**Comment by sananguliyev** [comment]
Hey @fulghum 

Yes, that was the first I have checked, and it was `SYSTEM` as expected. I am currently trying to fix this issue. That's something most of the BI tools are checking when they connect and due to that query it fails. Would it make process faster if I fix and make PR?

**Comment by fulghum** [comment]
Hey @sananguliyev, we would love a contribution for this fix! 🙏 If you're up for it, that would be really awesome. I haven't dug deep into this code yet, but seems like the fix should be fairly straightforward. 

You've probably already found [the `convert_tz.go` file that has the function implementation](https://github.com/dolthub/go-mysql-server/blob/f1bc6b807027ab15f7ef09c69c064a707d47de00/sql/expression/function/convert_tz.go). I mentioned the [unit tests in the `convert_tz_test.go` file](https://github.com/dolthub/go-mysql-server/blob/f1bc6b807027ab15f7ef09c69c064a707d47de00/sql/expression/function/convert_tz_test.go) earlier, and [the `TestSingleScript` function in `memory_engine_test.go`](https://github.com/dolthub/go-mysql-server/blob/4722c4cfd575069a5cd7731ddf628bc4c58f5fe4/enginetest/memory_engine_test.go#L205) is usually where I start debugging any issue – it's pretty easy to unskip that test function, have it run a SQL statement to trigger the issue, and debug through the code. 

Don't hesitate to ping us if you hit any snags or have any questions – we're happy to help! We're also pretty active on the [DoltHub Discord server](https://discord.com/invite/RFwfYpu) if you ever wanna drop by and discuss anything.

**Comment by sananguliyev** [comment]
#1537

**Comment by fulghum** [comment]
This was fixed in PR https://github.com/dolthub/go-mysql-server/pull/1537
