### ISSUE TITLE
navicat connect DB but can not edit

### ISSUE THREAD

**Issue by 464201213** [dolthub/go-mysql-server#1567]
![image](https://user-images.githubusercontent.com/49192825/215315939-76b05bb2-4603-471d-96ff-134b52477296.png
I use Navicat 16 for MySQL to connect the demo, but I can not edit  tables,i don't know why.

**Comment by timsehn** [comment]
Thanks for the report.

How are you connecting to `go-mysql-server` are you using Dolt or your own implementation?

**Comment by lxShaDoWxl** [comment]
Такая же проблема, запускал пример базы memory и не даёт редактировать выводит предупреждение "no primary key"
ошибка на сетевом уровне, вот более подробно
https://github.com/apache/shardingsphere/issues/3005

**Comment by lxShaDoWxl** [comment]
Сделал фикс. Есть вопрос по поводу sql/column.go строка 74, разве условие `reflect.DeepEqual(c.Default, c2.Default)` не всегда false будет? там всегда у одной колонки значение nil
