### ISSUE TITLE
unbound variable "v1" in query

### ISSUE THREAD

**Issue by hairyhenderson** [dolthub/go-mysql-server#1591]
I have a query like `SELECT * FROM t WHERE last_seen > ?`, and running `db.QueryRowContext(ctx, query, time.Now()).Scan(...)` gives me an error:

```
unbound variable "v1" in query
```

This looks similar to the issue #383, where it was [suggested](https://github.com/dolthub/go-mysql-server/issues/383#issuecomment-1067647556) that this could be fixed by prefixing a `"v"` to the ordinal on unnamed bindings.

And indeed, stepping through the failure I see the binding is being named `"1"`, and then the lookup for `"v1"` is missing.

**Comment by hairyhenderson** [comment]
FYI this fixes my issue completely: https://github.com/hairyhenderson/go-mysql-server/commit/6e8cbacdfc326c1b6a9a6e2239eee02d70e15768

**Comment by timsehn** [comment]
Submit a PR?

**Comment by hairyhenderson** [comment]
I've issued https://github.com/dolthub/go-mysql-server/pull/1592 - note that it's against the `v0.14.0` tag - `main` wasn't working for me and I'm about to hop on a flight.
