### ISSUE TITLE
Support for prepared statements

### ISSUE THREAD

**Issue by zachmu** [dolthub/go-mysql-server#172]
This is more important than we have been treating it, because there are many drivers that do this under the hood without clients explicitly asking for it. From https://github.com/liquidata-inc/go-mysql-server/issues/169

**Comment by tooolbox** [comment]
I know I gave this a thumbs-up, but I decided to also chime in and say that I ran into this 2 days ago and wasn't able to use `go-mysql-server` because of it 😞 

Not sure how much work it is to implement, but I would *love* to render my unit tests untethered to a database installation or docker container.

**Comment by tooolbox** [comment]
After #177 I decided to try again, ran into this one once more and wanted to give a little more context.

I use [golang-migrate](https://github.com/golang-migrate/migrate) for migrations, including tests.  That package, in turn, uses the [mysql driver](https://github.com/golang-migrate/migrate/tree/master/database/mysql).  When I attempt to perform a migration I get:

```
INFO: NewConnection: client 1
INFO: ConnectionClosed: client 1
ERROR: mysql_server caught panic:
prepared statements are not implemented
~/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.6.0/server/handler.go:97 (0x1afe358)
	com/liquidata-inc/go-mysql-server/server.(*Handler).ComPrepare: panic("prepared statements are not implemented")
~/go/pkg/mod/github.com/liquidata-inc/vitess@v0.0.0-20200807222445-2db8e9fb6365/go/mysql/conn.go:914 (0x18dbb7a)
	com/liquidata-inc/vitess/go/mysql.(*Conn).handleNextCommand: fld, err := handler.ComPrepare(c, queries[0])
~/go/pkg/mod/github.com/liquidata-inc/vitess@v0.0.0-20200807222445-2db8e9fb6365/go/mysql/server.go:472 (0x18f7a3c)
	com/liquidata-inc/vitess/go/mysql.(*Listener).handle: err := c.handleNextCommand(l.handler)
/usr/local/Cellar/go/1.14.3/libexec/src/runtime/asm_amd64.s:1373 (0x1068de0)
	goexit: BYTE	$0x90	// NOP

[mysql] 2020/09/23 19:49:09 packets.go:36: unexpected EOF
panic: try lock failed in line 0: SELECT GET_LOCK(?, 10) (details: invalid connection)
```

Not that you're going to handle that error directly, but just so you get an idea of an exact use case and what's blowing up.  I think `golang-migrate` is the most popular migration library, so it's not entirely out of left field.

**Comment by tooolbox** [comment]
Interesting.  The bleeding-edge, untagged version of that mysql driver has an `x-no-lock` parameter.  When I flip it on, golang-migrate buffers all the migrations and then I get a different failure:

```
panic: transaction start failed in line 0:  (details: Error 1105: unknown error: unsupported syntax: begin)
```

I guess transactions aren't supported?  I wrapped some of my migrations with `BEGIN;` and `END;` although laughably I don't think it does anything.  I'll try removing those statements.

**Comment by tooolbox** [comment]
Nope, looks like the driver [uses a transaction](https://github.com/golang-migrate/migrate/blob/master/database/mysql/mysql.go#L311) for setting the version number in the migrations table 😢

**Comment by zachmu** [comment]
Hi @tooolbox,

Begin and Commit parse without error, but don't do anything. Same with rollback. The engine doesn't model transaction boundaries / read isolation yet.

We're going to implement prepared statements in the near future, some time in the next month. Transaction support is a bit farther out.

**Comment by zachmu** [comment]
Prepare statement execution is now on master. The last piece, com_stmt_fetch (used by C API) is being implement now. Andy will close this out when it's done.

**Comment by tooolbox** [comment]
@zachmu I was waiting for this issue to close, but given that I'm not using the C API, should I take another stab at running my tests and see how golang-migrate behaves with this project standing in for MySQL?

(It's more work than just running a command, hence me asking before diving in again.)

Thanks!

**Comment by zachmu** [comment]
Prepared statements are now fully implemented, let us know if you find any issues with them.

Transactions are still a no-op with the in-memory database implementation.

**Comment by tooolbox** [comment]
Wow, fantastic!  I'll give it a go.

**Comment by llorllale** [comment]
Hi @zachmu - prepared statements are still listed as missing features

**Comment by hairyhenderson** [comment]
@llorllale that document in conjunction with the fact that this issue is closed confused me until I realized that I was attempting to use the in-memory database implementation, and getting strange errors. 😅
