### ISSUE TITLE
[Feature Request] Support for `INSERT INTO ... VALUE`

### ISSUE THREAD

**Issue by okhowang** [dolthub/go-mysql-server#1750]
SEE https://dev.mysql.com/doc/refman/5.7/en/insert.html#:~:text=VALUE%20is%20a%20synonym%20for%20VALUES%20in%20this%20context.%20Neither%20implies%20anything%20about%20the%20number%20of%20values%20lists%2C%20nor%20about%20the%20number%20of%20values%20per%20list.%20Either%20may%20be%20used%20whether%20there%20is%20a%20single%20values%20list%20or%20multiple%20lists%2C%20and%20regardless%20of%20the%20number%20of%20values%20per%20list.

**Comment by fulghum** [comment]
Hey @okhowang, thanks for opening this one. This was a really small change to our grammar, so I knocked it out real quick for you. It's built into our vitess fork now and I'll update the vitess version in go-mysql-server in just a few minutes. 

Let us know if there's anything else you need!
