### ISSUE TITLE
utf8mb3_tolower_ci not implemented

### ISSUE THREAD

**Issue by mikelee666** [dolthub/go-mysql-server#1771]
When importing mysql dump, I had a error:

mysql -uroot --protocol TCP --port 8039 < mysql_dump.sql 
ERROR 1105 (HY000) at line 35: The collation `utf8mb3_tolower_ci` has not yet been implemented

**Comment by timsehn** [comment]
We don't have that collation yet. @Hydrocharged will implement it today and get a release.

**Comment by bpf120** [comment]
@mikelee666 We'd love to learn about your use case too. Feel free to [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you want to chat.

**Comment by mikelee666** [comment]
> 

another Question: did the dolt which use as replication of mysql support api interface ?

**Comment by mikelee666** [comment]
Mysql also have UTF8MB4_GENERAL_CI, UTF8MB4_0900_AI_CI and so on, did the new release version implemented those?

**Comment by timsehn** [comment]
> Mysql also have UTF8MB4_GENERAL_CI, UTF8MB4_0900_AI_CI and so on, did the new release version implemented those?

These are the current supported collations: https://docs.dolthub.com/sql-reference/sql-support/miscellaneous#collations-and-character-sets

> Can I use DoltLab as a replication for mysql?

No. DoltLab's Dolt is offline. You need a running Dolt to act as a replica.

**Comment by mikelee666** [comment]
> > Mysql also have UTF8MB4_GENERAL_CI, UTF8MB4_0900_AI_CI and so on, did the new release version implemented those?
> 
> These are the current supported collations: https://docs.dolthub.com/sql-reference/sql-support/miscellaneous#collations-and-character-sets

Could I miss database "mysql" by setting REPLICATE_IGNORE_TABLE, what side effect may happen?

**Comment by timsehn** [comment]
> > > Mysql also have UTF8MB4_GENERAL_CI, UTF8MB4_0900_AI_CI and so on, did the new release version implemented those?
> > 
> > 
> > These are the current supported collations: https://docs.dolthub.com/sql-reference/sql-support/miscellaneous#collations-and-character-sets
> 
> Could I miss database "mysql" by setting REPLICATE_IGNORE_TABLE, what side effect may happen?

I don't think by default the mysql database is replicated.

**Comment by timsehn** [comment]
This collation is in the 1.1 release.

**Comment by mikelee666** [comment]
> This collation is in the 1.1.0 release.

thx
