### ISSUE TITLE
Combine index lookups on different columns of multi-column indexes with different operators

### ISSUE THREAD

**Issue by zachmu** [dolthub/go-mysql-server#179]
Right now expressions on the columns of a key with different operators, such as:

`select * from sales_estimate where act_symbol = 'AAPL' and retrieval_date < '2017-11-01';`

Assuming that act_symbol and retrieval_date are two columns in the key, we can't form an index lookup on these terms because the two comparisons use different operators (= and <). Fixing this will take a little thought -- none of the current index interfaces address this possibility for multi-key indexes.

**Comment by zachmu** [comment]
This is the next major expansion in usefulness for indexes

**Comment by Hydrocharged** [comment]
This is now supported!
