### ISSUE TITLE
Extracting update query columns

### ISSUE THREAD

**Issue by abbnaseri** [dolthub/go-mysql-server#1800]
Could you tell me how i can extract which columns the update query wants to update and what are their values? By the way, huge thanks for your awesome project.

**Comment by abbnaseri** [comment]
Hey @zachmu, Thanks for your response. In our project we want to parse the sql queries that we are receiving and extract its components and then use those components to build a request and send it to another service for database updates. there is a legacy service which we are trying to detach it from real database. for example if this is the query we are receiving: 

`UPDATE users SET email = "example@example.com" WHERE id = 1;`

we want to know that this is an 'update' query and it tries to update 'email' column based on id = 1 condition. I read the BACKEND.md but i didn't get which interface i should implement. I'll be grateful if you help me with that.

**Comment by timsehn** [comment]
I think what you really want is the Vitess. This is our fork;

https://github.com/dolthub/vitess

That handles query parsing in go-mysql-server.

**Comment by abbnaseri** [comment]
Yeah I came across this project earlier but i didn't understand how it can solve my problem. What we want is all MySQL functionality with this exception that for queries we need all their components for building the requests and for response we must return valid MySQL responses/errors so that the legacy project doesn't feel it is a mock MySQL.

**Comment by timsehn** [comment]
Going to cvlose this as I think we answered your question.
