### ISSUE TITLE
Support for VALUES in INSERT ... ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by Harrison-Miller** [dolthub/go-mysql-server#191]
In mysql there is a specific version of the VALUES function that goes after the ON DUPLICATE KEY UPDATE statement that references a named column in the INSERT portion of the statement: https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

Currently running a command that uses this feature will result in: `unknown error: unsupported syntax: values(column_name)`

My guess is this is happening somewhere in vitess which may not support this feature. I may look into it myself but modifying vitess sounds like quite the deep dive.

Example test case:
```
INSERT INTO mytable (i,s) VALUES (1, "foo"), (2, "bar"), (3, "qux")
ON DUPLICATE KEY UPDATE s= CONCAT(VALUES(i), VALUES(s));
```

**Comment by zachmu** [comment]
This is now in master. Thanks for the contribution!

**Comment by Harrison-Miller** [comment]
@zachmu this is a separate issue from my PR.

**Comment by zachmu** [comment]
My mistake!

I can probably get the vitess changes in the near future, stay tuned.

**Comment by zachmu** [comment]
This was fixed some time ago, let us know if you find any issues with it.
