### ISSUE TITLE
Please cut a new release with the new group name

### ISSUE THREAD

**Issue by Harnish** [dolthub/go-mysql-server#209]
the 0.6.0 release points to liquidata-inc causing an issue with new projects attempting to use this project:
```
        github.com/dolthub/go-mysql-server: github.com/dolthub/go-mysql-server@v0.6.0: parsing go.mod:
        module declares its path as: github.com/liquidata-inc/go-mysql-server
                but was required as: github.com/dolthub/go-mysql-server
```

**Comment by zachmu** [comment]
Thanks for the heads up! We will do this very shortly.

**Comment by zachmu** [comment]
Sorry about that, we didn't realize the redirects didn't work with new projects :(

New release is here:

https://github.com/dolthub/go-mysql-server/releases/tag/0.7.0

**Comment by yjjnls** [comment]
I still get the same error. It still find 0.6.0 instead of 0.7.0

**Comment by sluberriaga** [comment]
I think the 0.7.0 version is incorrectly tagged, pulling from the commit works @zachmu
