### ISSUE TITLE
go mod tidy error

### ISSUE THREAD

**Issue by iwanlebron** [dolthub/go-mysql-server#2225]
get https://sourcegraph.com/sourcegraph/appdash?go-get=1
get https://sourcegraph.com/sourcegraph/appdash?go-get=1: 404 Not Found (0.369s)
get https://sourcegraph.com/sourcegraph/appdash?go-get=1
get https://sourcegraph.com/sourcegraph/appdash?go-get=1: 404 Not Found (0.203s)
go: github.com/go-kit/kit@v0.10.0 requires
	sourcegraph.com/sourcegraph/appdash@v0.0.0-20190731080439-ebfcffb1b5c0: unrecognized import path "sourcegraph.com/sourcegraph/appdash": reading https://sourcegraph.com/sourcegraph/appdash?go-get=1: 404 Not Found

**Comment by nicktobey** [comment]
Hi Iwan, can you provide us with more context for this issue? Did you encounter this while installing/updating GMS?

I ran `go get github.com/go-kit/kit@v0.10.0` at HEAD and was not able to reproduce this issue.

**Comment by fulghum** [comment]
Hi Iwan, we haven't heard back in a month on this issue, so I'm going to close it out. Feel free to reopen and provide the information Nick asked for if you're still seeing this issue.
