### ISSUE TITLE
DB Startup Config File - values not utilized

### ISSUE THREAD

**Issue by chrisfw** [dolthub/go-mysql-server#230]
Hi,

I am trying to override the default values when starting the mysql server using the --config parameter and yaml config definition as described in 
[the docs](https://www.dolthub.com/docs/reference/cli/#dolt-sql-server_description). (Example below)  The file is apparently loaded (I performed a test using a non-existent file name which did generate a file not found error), yet all of the default values are still being utilized.  I changed the user name, timeouts, etc., yet the original defaults are still be used on startup.  What am I missing here?

```log_level: info
behavior:
read_only: false
autocommit: true

user:
name: root
password: ""

listener:
host: localhost
port: 3306
max_connections: 1
read_timeout_millis: 30000
write_timeout_millis: 30000

databases: []
```

**Comment by zachmu** [comment]
Chris,

This is when running `dolt sql-server`, correct?

Can you paste the exact command you're running and any output?

**Comment by chrisfw** [comment]
Here is the info Zach with the command at the end after illustrating file contents.

Thanks,
Chris

```
5ss2rn2:ip-to-country cwhelan$ ls -l
total 8
-rw-r--r--  1 cwhelan  staff  204 Nov 13 07:44 mysql.conf
5ss2rn2:ip-to-country cwhelan$ cat mysql.conf 
log_level: info
behavior:
read_only: false
autocommit: true

-user:
name: toot
password: ""

listener:
host: localhost
port: 3306
max_connections: 1
read_timeout_millis: 40000
write_timeout_millis: 40000
5ss2rn2:ip-to-country cwhelan$ dolt sql-server --config mysql.conf 
Starting server with Config HP="localhost:3306"|U="root"|P=""|T="30000"|R="false"|L="info"

```

**Comment by chrisfw** [comment]
Hi Zach,

Just wondering when you may have an opportunity to look into this issue?

Regards,
Chris

**Comment by zachmu** [comment]
Hi Chris,

I think what's happening is that you don't have correct indentation correct in your YAML file. The lines after `behavior:`, `user:` and `listener:` need to be indented, or else they aren't consider part of those config blocks, which they need to be for them to be properly evaluated. I get the same behavior when I use your yaml as above, with no indentation on any line.

Try with this file (preserve indentation):

```
log_level: info

behavior:
  read_only: false
  autocommit: true

user:
  name: toot
  password: ""

listener:
  host: localhost
  port: 3306
  max_connections: 1
  read_timeout_millis: 40000
  write_timeout_millis: 40000
```

**Comment by chrisfw** [comment]
Thanks Zach, that was it!  Sometimes I really despise YAML!
