### ISSUE TITLE
Server error message compatibility when doing INSERT

### ISSUE THREAD

**Issue by xiaost** [dolthub/go-mysql-server#2344]
Hi, 

[go-mysql-server](https://github.com/dolthub/go-mysql-server) is great, and I'm using it for UT.

Here to report 2 cases I encountered today.  
Appreciate that if you can unify the code and msg for better compatibility.

**Case 1 - unknown column (code / msg mismatch)**

How to reproduce:
```
CREATE TABLE `test_table` ( `id` INT NOT NULL PRIMARY KEY, `v` INT );
INSERT INTO `test_table` (`id`, `v_`) VALUES (1, 2)
```

What I got  (github.com/dolthub/go-mysql-server v0.17.0)
```
Error 1105: invalid column name v_
```

What I expected (mysql 8.3.0)
```
Error 1054: Unknown column 'v_' in 'field list'
```

**Case 2 - Table not found (msg mismatch)**
This one is minor since codes are the same, just the issue of msg

How to reproduce:
```
INSERT INTO `test`.`no_such_table` (`id`, `v`) VALUES (1, 2)
```

What I got  (github.com/dolthub/go-mysql-server v0.17.0)
```
Error 1146: table not found: no_such_table
```

What I expected (mysql 8.3.0)
```
Error 1146: Table 'test.no_such_table' doesn't exist
```

**Comment by nicktobey** [comment]
The specific incompatibility that you outlined has been fixed.

There may be other places where we return an incorrect MySQL error code. If you encounter any, please let us know and we'll fix them rightaway.

**Comment by xiaost** [comment]
Sure, will let you know if any issues found. 
Thanks for your quick reply. 👍🎉🙏
