### ISSUE TITLE
Running multiple migrations in a transaction

### ISSUE THREAD

**Issue by alecsammon** [dolthub/go-mysql-server#2396]
When using the memory database and running migrations to rename both columns and tables this can fail depending on the order of the operations.

If the order (inside a transaction) is:
1. Rename column
2. Rename table
Then the column rename is not used in the resulting state of the database.

If the order is:
1. Rename the table
2. Rename the column
Then this is ok.

I created a draft PR with test cases to show the bug here: https://github.com/dolthub/go-mysql-server/pull/2395

**Comment by jycor** [comment]
Hey @alecsammon, thanks for the detailed issues and great repro!

I'm able to reproduce the issue, and am tracking down what's gone awry.
Hoping to make some progress on this today.

**Comment by alecsammon** [comment]
@jycor  - thanks so much for the quick resolution to this one.
