### ISSUE TITLE
unsupported syntax: create database mapping

### ISSUE THREAD

**Issue by eqinox76** [dolthub/go-mysql-server#250]
Love this project!

While trying it out i got this error 
```
Error 1105: unknown error: unsupported syntax: create database mapping
```
when issuing
```sql
CREATE SCHEMA IF NOT EXISTS mapping;
```
against a in memory instance.
```go
	driver := sqlserver.NewDefault()
	driver.AddDatabase(memory.NewDatabase("default"))

	config := server.Config{
		Protocol: "tcp",
		Address:  "localhost:3306",
		Auth:     auth.NewNativeSingle("root", "pass", auth.AllPermissions),
	}

	s, err := server.NewDefaultServer(config, driver)
	if err != nil {
		panic(err)
	}

	go func() {
		err := s.Start()
		if err != nil {
			panic(err)
		}
	}()
```

I am using:
github.com/dolthub/go-mysql-server v0.6.1-0.20201228192939-415fc40f3a71
github.com/go-sql-driver/mysql v1.5.0

For now i can work around it by creating the schemas via `driver.AddDatabase()`.

**Comment by zachmu** [comment]
CREATE DATABASE statements are not currently supported. They must be supplied by implementors.

Database is actually the root object in the interface hierarchy, so we would need to create an additional layer of abstraction, something that knows how to create a Database, and wire it in. So it's not as simple to add this as some other features.

Definitely on our radar though, and we would consider any PRs if you wanted to patch this yourself.

**Comment by zachmu** [comment]
`Create Database` is now supported
