### ISSUE TITLE
LastInsertId always returns 0

### ISSUE THREAD

**Issue by eqinox76** [dolthub/go-mysql-server#251]
When running several insert commands like
```go
result, err := db.Exec("INSERT INTO mytable SET number = 18;")
id, err := result.LastInsertId()
```
Against a simple table like 
```mysql
CREATE TABLE IF NOT EXISTS mytable (
id int unsigned NOT NULL AUTO_INCREMENT,
number int unsigned DEFAULT NULL,
PRIMARY KEY (id),
) DEFAULT CHARSET=utf8;
```
the returned id is always 0. While the go-mysql-driver returns the correct pkey.

Used libraries:
github.com/dolthub/go-mysql-server v0.6.1-0.20201228192939-415fc40f3a71
github.com/go-sql-driver/mysql v1.5.0

**Comment by zachmu** [comment]
Thanks for the bug report.

LastInsertId is not currently populated into the query response, which is why it's always 0.

It shouldn't be that hard to fix. I'll take a look and get back to you.

**Comment by Drabuna** [comment]
Any updates on this one?

**Comment by karagog** [comment]
I'm also blocked by this issue. This is a pretty fundamental gap in functionality which prevents this from being a "drop-in replacement" for a real MySQL server. Can this be highly prioritized?

**Comment by zachmu** [comment]
Hi folks,

We have this in our docket now, should be part of a release coming pretty soon. Sorry for the lack of updates!

Zach

**Comment by zachmu** [comment]
ROW_COUNT(), FOUND_ROWS(), and LAST_INSERT_ID() are all implemented in the latest release:

https://github.com/dolthub/go-mysql-server/releases/tag/v0.9.0

The lastInsertId field on the OK response packet is still not populated, but this value can now be fetched with `select last_insert_id()`. This will be fixed in an upcoming patch release, but please use the workaround if possible for now. I'll keep this open until it's fully implemented.

**Comment by eqinox76** [comment]
Wuhu thank you very much for adding this feature!

**Comment by paralin** [comment]
I've tried to work around this a few ways, but it would be much easier of LastInsertId was filled

**Comment by timsehn** [comment]
@paralin , we prioritize features as they impact our main project [Dolt](https://www.doltdb.com).

You have some options to get this prioritized:
1. Make an open source contribution to this project.
2. GitHub Sponsor the DoltHub organization to move it up our priority stack
3. Wait until a paying customer has this feature request in Dolt
4. Wait until we have slack to implement this in our small engineering team

We'll eventually get to everything as long as we can stay in business.

**Comment by paralin** [comment]
Hi @timsehn thanks for your great work. I'm already aware of your business model, my comment was less a "hurry up" and more a "yes this is relevant to me," and I'll most likely end up submitting a PR with the fix soon. No need to send the "pay us if you want it faster" blurb, I fully get it. Thanks again.

**Comment by timsehn** [comment]
We would appreciate the contribution.

**Comment by zachmu** [comment]
This is fixed in the latest release. Grab v0.10.0 to get it.

**Comment by paralin** [comment]
Thanks!
