### ISSUE TITLE
Better support for parallel tests

### ISSUE THREAD

**Issue by egtann** [dolthub/go-mysql-server#253]
First off, huge thank you for this project. Integration tests run _dramatically_ faster with this in-memory DB than in MySQL.

We have a large number of integration tests and would like to adopt go-mysql-server for this. We use `t.Parallel()` throughout to reduce the running time. We also have a 540kb SQL file that we use to seed the database for our tests.

To prevent tests running in parallel from affecting one another, each test gets its own copy of the database with a slightly different name, e.g. `test_1`, `test_2`. Each database needs to be seeded using this SQL file, and currently we do this with the following:

```
func seedDB(
	user, pass, host, dbName string,
	port int,
	seedData []byte,
) error {
	cmd := exec.Command("mysql", "-h"+host, fmt.Sprintf("-P%d", port),
		"-p"+pass, "-u"+user, "-D"+dbName)
	cmd.Stdin = bytes.NewReader(seedData)

	var out, stderr bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		fmt.Printf("run: %+v\n: %+v, %v\n", out.String(),
			stderr.String(), err)
		return err
	}
	return nil
}
```

This approach is very slow, and takes roughly 4s per test on Ubuntu 20.10. Across a large number of tests, this adds up to a large amount of time.

If we could seed the database with SQL directly in Go or otherwise copy and rename the database on each test, that would dramatically speed up our test runs. Any chance a solution like this would be accepted?

**Comment by zachmu** [comment]
Hi @egtann,

It should be possible to seed the database directly with Go today. You just execute statements directly against the database engine in Go, not through the mysql command line. There are examples of how this works in the enginetests package, but briefly it will be something like this:

```
db := memory.NewDatabase(name)
catalog := sql.NewCatalog()
catalog.AddDatabase(db)
catalog.AddDatabase(information_schema.NewInformationSchemaDatabase(catalog)) //  optional
a := analyzer.NewDefault(catalog)
engine := sqle.New(catalog, a, new(sqle.Config))

...
for _, s: = range (statements) {
    _, iter, err := engine.Query(sql.NewEmptyContext(), s)
    require.NoError(t, err)
    _, err = sql.RowIterToRows(iter)
    require.NoError(t, err)
}
```

I'm not sure how much faster this will be in practice, you'll have to try it to find out.

**Comment by egtann** [comment]
That is great to know @zachmu. I wasn't aware I could do this, but it makes perfect sense. Thank you for your help! I'll close this issue now as it is resolved.
