### ISSUE TITLE
Analyzer becomes very slow for many joins

### ISSUE THREAD

**Issue by ligustah** [dolthub/go-mysql-server#266]
Hey there,

Been playing around with this library for a pet project of mine. Really enjoying it so far, so thanks for your work!

I ran into an issue with the analyzer. I haven't quite figured out exactly what's causing it, but for a certain number of joins the analyzer seems to run into an expensive loop somewhere. I created a small program to demonstrate the issue:

https://gist.github.com/ligustah/2f058e3dc6635bd113048301d1c227e7

Tried profiling/tracing to see where it gets stuck, but it didn't really come out conclusive for me. Maybe you can have a look or point me in the right direction?

(edit: worth noting, it doesn't seem to be an endless loop. in another test on my machine the query would complete after like 6 minutes. on a mysql server running in docker it completes within milliseconds)

**Comment by zachmu** [comment]
Hi @ligustah,

This is almost certainly a result of inefficiencies in the join planning algorithm. The current algorithm to construct a join plan given a table ordering is pretty wasteful and duplicates a lot of work. We have tests of 5 tables, but apparently 7 pushes it over the edge. The algorithm is brand new and has not been optimized yet.

If you wanted to try to take a pass at making it faster, this is where you should look:

https://github.com/dolthub/go-mysql-server/blob/master/sql/analyzer/join_search.go#L332

I have ideas for making the complex tree building process used here unnecessary, but it involves larger changes to the analyzer as a whole. So for now, you should focus on pruning the search space in this algorithm.

More about the algorithm in this blog post:

https://www.dolthub.com/blog/2020-12-28-join-planning/

Let me know what else I can tell you,

Zach

**Comment by ligustah** [comment]
Hey @zachmu,
thanks for getting back to me and pointing me in the right direction. I've been reading through the blog and also looking at some other material, so I'm starting to get a better understanding of the issue. I might take a stab at it and just see if I can make it any faster, but for now will content with trying to avoid having too many joins.

Do you already have a prospective timeline for when those bigger changes are going to happen?

**Comment by zachmu** [comment]
No, I don't have an estimate for that yet.

**Comment by zachmu** [comment]
@ligustah We've now rewritten the join order analyzer, and it works for 10 tables in under a second now. We haven't done a release of the package since then, so you'll need to get the version @master for this optimization. Let me know if you have any trouble with it.

**Comment by ligustah** [comment]
Wow, that's amazing! I'll definitely check it out. Thank you 🙇
