### ISSUE TITLE
Any plan to make a new patch release?

### ISSUE THREAD

**Issue by licy183** [dolthub/go-mysql-server#2790]
Hello, thanks for your work on this tool library. I've recently been using this library in my unit tests, but I've been having issues with concurrent map reads and writes. Is there any plan to cherry-pick dolthub/go-mysql-server@9e760caafa8e0bf4b203e1036cc8bc3ea20dbb65 to `v0.18.x` and make a new patch release?

**Comment by timsehn** [comment]
I think we should just do a release. @zachmu will do that today.

**Comment by haneul** [comment]
@timsehn @zachmu are you releasing one soon?

**Comment by zachmu** [comment]
Yes, sorry :)

**Comment by zachmu** [comment]
Release 0.19.0 is out now. Need to update the release notes but you can begin using it now.

**Comment by zachmu** [comment]
Release notes updated now. Closing this.
