### ISSUE TITLE
Start/Stop not propagating errors?

### ISSUE THREAD

**Issue by karagog** [dolthub/go-mysql-server#346]
This seems like a bug to not propagate the error from the listener in Server.Start/Stop.

https://github.com/dolthub/go-mysql-server/blob/bee967dcfcd93e179adc8802a05994f508a5b05b/server/server.go#L119

**Comment by zachmu** [comment]
Hi @karagog,

This isn't a bug because the Listener.Accept() method itself doesn't return anything. There's no way for Start/Stop to return an error with the current implementation. We reserve the right to begin returning errors from those methods in the future, since they do IO.

Zach
