### ISSUE TITLE
Question/Feature Request: How can I increase the parallelism of expression evaluation?

### ISSUE THREAD

**Issue by andremarianiello** [dolthub/go-mysql-server#355]
I have a situation where I have a custom SQL function that is a bit slow (like a single network request slow). Because rows are demanded one at a time from a RowIter, these expressions are evaluated one at a time, meaning we run these network requests one at a time. I would like some way to evaluate these rows in parallel as this would greatly improve the speed of my queries. I can't prefetch everything because I do not have all the data needed for all the network requests until query execution. A while back I tried making a custom SQL plan node which wraps another node and prefetches rows from its child node in parallel, but I ran into some issues where the RowIter implementation I was calling misbehaved as it was not threadsafe. Do you have any suggestions for me? Was the parallel prefetch node a good/bad idea? I really appreciate your help with this, thanks.

**Comment by zachmu** [comment]
So I would not expect a random RowIter to be threadsafe, no. (Some are, some not)

But you should definitely be able to pull results from a RowIter on a single thread, then fan those rows out to a pool of workers to do the expensive part in parallel. That should work fine!

The only parallelism in the engine is at the table layer, basically fetching the partitions of a table in parallel. You can check out the Exchange node for details on that, but it's unlikely to help this particular situation.

**Comment by andremarianiello** [comment]
> But you should definitely be able to pull results from a RowIter on a single thread, then fan those rows out to a pool of workers to do the expensive part in parallel. That should work fine!

Can you expand more on this? I don't see how this could help but I could very well be misunderstanding what you are suggesting. Thanks!

**Comment by zachmu** [comment]
I might not understand the problem!

So you have a function call that is slow, and you want to call it on a bunch of rows in parallel. If your function call is a lot slower than getting a row from the child node then this should be faster:

```go
for {
  row, err = childIter.Next()
  if err != nil {
    return err
  }
  rowChan <- row
}
```

Assuming you have a bunch of goroutines reading from `rowChan`, they can each pull rows off the channel as they come off the iterator, then do the slow work in parallel.

**Comment by andremarianiello** [comment]
The slow function call I have is a custom SQL function. Here is an fake query to demonstrate what I mean:

```sql
select resolve_entity(t.id) from t
``` 

In this example resolve_entity is a custom SQL function that I have registered with the engine. It evaluates its argument, uses that argument in a network RPC (think GET /api/thingy/{id}) and returns something from the RPC response as the result of the function. This mean that the slow part of your example is the `.Next()` call, because that synchronously calls `.Next()` on its children recursively until reaching the Project node which has the resolve_entity call expression. `.Next()` on that Project node will evaluate that expression synchronously, blocking until we get a network response. Then that response is used to construct the value that gets returned by the resolve_entity, which is then used to construct the row which is returned by the `.Next()` call, bubbling up to the top. Does my description of the behavior of `.Next()` and expression evaluation seem accurate?

**Comment by zachmu** [comment]
Yes, that is how the engine works right now.

What you want to do is replace the Project node with one that does basically the same thing, except fetches child.`Next()` rows asynchronously, and does the projection evaluations asynchronously as well. Does that make sense?

**Comment by andremarianiello** [comment]
Yup that makes perfect sense. Do you think that is better than custom a sql.Node that wraps any existing sql.Node to demand rows in parallel? Because Project nodes aren't the only ones that do expressions evaluation, right? Filter, Group, Sort, etc. all eval expressions so I want the ability to demand rows in parallel from any node that has an expression with my function in it.

**Comment by zachmu** [comment]
Yes, a good way to structure this would be to implement a wrapper that pulls rows from a child iterator and feeds them in parallel to the Eval() logic of the original wrapped node. Would require quite a bit of restructuring to make it work this way though. Basically you would need to define a new interface for Project, Filter, etc. nodes so that the logic that currently lives in their RowIter implementations can be provided by the Node itself. Probably some complicated details there, but I think it should be possible.

**Comment by andremarianiello** [comment]
Ooh very clever, it sounds like the solution you are describing would run Eval in parallel but not Next. I hadn't considered that but it sounds like it would get around the lack of threadsafety in Next() so I am intrigued. If I get a chance to do this and come up with a solution, would you want to see a PR? Or is this to niche a use-case to want to support?

**Comment by zachmu** [comment]
Going to close this out for now, please reopen with any questions.
