### ISSUE TITLE
Unbound variables in subqueries

### ISSUE THREAD

**Issue by paralin** [dolthub/go-mysql-server#383]
When using the "driver" package, I kept running into the following errors:

```
DEBU[0115] [6.873ms] [rows:-] SELECT count(*) FROM information_schema.tables WHERE table_schema = 'test-db' AND table_name = 'entries' AND table_type = 'BASE TABLE' 
DEBU[0115] [0.853ms] [rows:0] CREATE TABLE `entries` (`id` bigint AUTO_INCREMENT,`value` bigint,PRIMARY KEY (`id`)) 
ERRO[0115] unbound variable "v1" in query: [0.778ms] [rows:0] INSERT INTO `entries` (`value`,`id`) VALUES (4,1) 
ERRO[0115] unbound variable "v1" in query: [0.614ms] [rows:0] INSERT INTO `entries` (`value`,`id`) VALUES (10,2) 
ERRO[0115] unbound variable "v1" in query: [0.622ms] [rows:0] INSERT INTO `entries` (`value`,`id`) VALUES (30,3) 
```

The fix appears to be changing `driver/value.go` to add a "v" prefix to ordinal placeholder values:

```
                        name = "v"+strconv.FormatInt(int64(v.Ordinal), 10)
```

... because the SQL plan code appears to expect "v1" "v2" and so on.

**Comment by zachmu** [comment]
@paralin,

Can you provide a short program that reproduces this problem? We have end-to-end tests of bind variables, but it seems like we are missing something.

Thanks!

Zach

**Comment by paralin** [comment]
@zachmu no problem, will try to split things up and get a reproduce

**Comment by paralin** [comment]
@zachmu I still don't have a reproduce but this commit fixes it 100%: https://github.com/paralin/go-mysql-server/commit/2fe0a7536bc52ea5c6b2b921d77392aa4307b231

**Comment by okhowang** [comment]
subquery with bindvar has same error
run with `_example/main.go`
```golang
	db, err := sql.Open("mysql", "root@tcp(localhost:3306)/mydb")
	if err != nil {
		panic(err)
	}
	var name string
	err = db.QueryRow("select exists(select name from mytable where name=?)", "John Doe").Scan(&name)
	if err != nil {
		panic(err)
	}
	fmt.Println(name)
```
```
Error 1105: unbound variable "v1" in query
```

**Comment by zachmu** [comment]
Seems likely that bindvars are not propagating to subqueries.

@max-hoffman, please investigate as part of your work on prepared query optimization

**Comment by darluc** [comment]
Met the same error.

**Comment by timsehn** [comment]
@max-hoffman Have you made any progress here? Seems like a real popular bug :-)

**Comment by max-hoffman** [comment]
This PR  https://github.com/dolthub/go-mysql-server/pull/795 implements prepared statements and doubles our testing coverage for `BindVar`s, including subqueries. Hopefully we will merge and release in the next week.

**Comment by paralin** [comment]
@max-hoffman Thanks again for all your work on this.

**Comment by zachmu** [comment]
> This PR #795 implements prepared statements and doubles our testing coverage for `BindVar`s, including subqueries. Hopefully we will merge and release in the next week.

Max, let's address this bug separately from the above PR. Bindvars not propagating to subqueries is a very specific issue that has nothing to do with saving the query plan for efficiency between executions.

**Comment by max-hoffman** [comment]
cherry picked subquery specific fixes in this PR: https://github.com/dolthub/go-mysql-server/pull/871

**Comment by paralin** [comment]
@max-hoffman I still have the issue on "main":

```
[rows:0] CREATE TABLE `entries` (`id` bigint AUTO_INCREMENT,`value` bigint,PRIMARY KEY (`id`)) 
unbound variable "v1" in query: [0.400ms] [rows:0] INSERT INTO `entries` (`value`,`id`) VALUES (4,1) 
unbound variable "v1" in query: [0.265ms] [rows:0] INSERT INTO `entries` (`value`,`id`) VALUES (10,2) 
unbound variable "v1" in query: [0.265ms] [rows:0] INSERT INTO `entries` (`value`,`id`) VALUES (30,3) 
```

The issue is resolved if I apply this patch:

```
From d18204a140a5ba96b18c381af3c5323234f45bd7 Mon Sep 17 00:00:00 2001
From: Christian Stewart <christian@paral.in>
Date: Fri, 23 Apr 2021 05:51:24 -0700
Subject: [PATCH] fix(driver): add v prefix to ordinal values

Signed-off-by: Christian Stewart <christian@paral.in>
---
 driver/value.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/driver/value.go b/driver/value.go
index 4f0e1fdf..8dc4dad4 100644
--- a/driver/value.go
+++ b/driver/value.go
@@ -93,7 +93,7 @@ func namedValuesToBindings(v []driver.NamedValue) (map[string]sql.Expression, er
 	for _, v := range v {
 		name := v.Name
 		if name == "" {
-			name = strconv.FormatInt(int64(v.Ordinal), 10)
+			name = "v" + strconv.FormatInt(int64(v.Ordinal), 10)
 		}
 
 		b[name], err = valueToExpr(v.Value)
-- 
2.35.1

```

**Comment by max-hoffman** [comment]
@paralin Can you share more info for how to reproduce the error? This seems like it deserves a new issue.

Do you `ComPrepare` ```INSERT INTO INSERT INTO `entries` (`value`,`id`) VALUES (?,?)```, and then exec with row values?

**Comment by paralin** [comment]
@max-hoffman I'm running it with something like this:

```go
	printQuery := func(e *sqle.Engine, query string) int {
		sqlCtx := buildSqlCtx()
		t.Logf("QUERY: %s", query)
		_, r, err := e.Query(sqlCtx, query)
		if err != nil {
			t.Fatal(err.Error())
		}
		var nrows int
		for {
			row, err := r.Next(sqlCtx)
			if err == io.EOF {
				break
			}
			if err != nil {
				t.Fatal(err.Error())
			}
			nrows++
			for ci, col := range row {
				t.Logf("COL %d: %v", ci, col)
			}
		}
		t.Logf("END QUERY: %d rows", nrows)
		r.Close(sqlCtx)
		return nrows
	}

```

which calls

```go
	return e.QueryWithBindings(ctx, query, nil)
```

**Comment by zachmu** [comment]
I think we have pretty good confidence that bindvars are being correctly propagated everywhere we know of now. If you find specific cases where this isn't true, please open another issue.

**Comment by paralin** [comment]
@zachmu Thanks!
