### ISSUE TITLE
Error: Unsupported feature: LIMIT with non-integer literal

### ISSUE THREAD

**Issue by jnu** [dolthub/go-mysql-server#439]
Getting the following error:

```
Error 1105: unknown error: unsupported feature: LIMIT with non-integer literal
```

Even though the query I'm running actually does use an integer, it's just interpolated.

Minimal repo:
```go
_, err := db.Query(`SELECT * FROM foo LIMIT ?`, 10)
// err is "Error 1105: unknown error: unsupported feature: LIMIT with non-integer literal"
```

(maybe the error means non-literal integers are not supported? using `LIMIT 10` instead of interpolating works.)

**Comment by zachmu** [comment]
Thanks for the report, this is definitely a bug

I have a fix, should get it released in the next few days

**Comment by jnu** [comment]
awesome, thank you!
