### ISSUE TITLE
Support Insert opeartion for sqlx.

### ISSUE THREAD

**Issue by wang-sy** [dolthub/go-mysql-server#443]
I use `github.com/dolthub/go-mysql-server v0.9.0`

When I use  sqlx to insert data, into the  `dolthub/go-mysql-server` database.
I can't get result.LastInsertID(), it always return  `id, err = 0, nil`

**Comment by zachmu** [comment]
This is fixed on master, but we haven't done a release in a while.

**Comment by zachmu** [comment]
Just did a new release, grab v0.10.0 and this should work. Let us know if it doesn't.
