### ISSUE TITLE
anyone writing the rocksdb backend?

### ISSUE THREAD

**Issue by hiqsociety** [dolthub/go-mysql-server#463]
anyone writing the rocksdb backend?

**Comment by zachmu** [comment]
Not that we know of, certainly not us

**Comment by hiqsociety** [comment]
will u guys write the rocksdb backend? or how do we start writing it?

**Comment by zachmu** [comment]
We don't plan to write any backend except the included in-memory one.

We're happy to give you pointers if you want to start another one.

Check out core.go for the main interfaces you need to implement.

Keep in mind that the interfaces aren't guaranteed stable until we hit 1.0, probably some time late this year.

**Comment by hiqsociety** [comment]
sounds great! just went through core.go

possible to give a boiler plate of sorts so i can complete the rest?

**Comment by hiqsociety** [comment]
@zachmu possible to give some boilerplate pointers?

**Comment by superdolt** [comment]
@zachmu hi, any pointers?

**Comment by zachmu** [comment]
We can't really support development of other backends beyond saying use the other implementations (dolt, in-memory database) as examples.

I can answer specific questions you have about the interfaces and how to implement them.

**Comment by zachmu** [comment]
I'm going to close this out, since we don't have any plans for development of other DB backends besides Dolt and the in-memory one.
