### ISSUE TITLE
Can a Table implement sql.IndexAddressableTable without implementing sql.DriverIndexableTable?

### ISSUE THREAD

**Issue by andremarianiello** [dolthub/go-mysql-server#476]
I have an implementation of Table that also implements IndexAddressableTable but not DriverIndexableTable. When using this table in a the join node is correctly being replaced with an IndexedJoin node, and the table node is being replaced with an IndexedTableAccess as expected. However, the trackProcess rule is wrapping my table with a ProcessTable node which no longer implements IndexAddressableTable. This causes the IndexedTableAccess.RowIter to return ErrNoIndexableTable. Looking at the trackProcess rule, it seems like a similar concern was addressed because it takes special care of DriverIndexableTable nodes, but not IndexAddressableTable nodes. Should trackProcess be handling IndexAddressableTable nodes, or should I be implementing DriverIndexableTable (even though I don't think that is correct for my use-case).

**Comment by zachmu** [comment]
I think this is a bug. Can you submit a patch?

**Comment by andremarianiello** [comment]
Will do

**Comment by zachmu** [comment]
Enough time has passed that I'm not certain that this bug still applies, and we definitely do not implement the Driver* interfaces in dolt, where indexed lookups work. Please reopen an issue if you can get a working repro demonstrating a defect here.
