### ISSUE TITLE
Cannot transform IndexedTableAccess nodes

### ISSUE THREAD

**Issue by andremarianiello** [dolthub/go-mysql-server#478]
The WithChildren() function of IndexedTableAccess expects an IndexAddressableTable to be passed in as the child. However, it's Children() function is simply the Children() function of it's anonymously embedded ResolvedTable, which returns 0 children. This causes errors in code that expects the output of Children() to be valid input to WithChildren(). It looks like IndexedTableAccess should have it's own Children() implementation that returns its ResolvedTable node.

**Comment by zachmu** [comment]
Can you get us test case that demonstrates the issue you're talking about?

**Comment by andremarianiello** [comment]
Will do
