### ISSUE TITLE
Cannot use expression index in indexed join

### ISSUE THREAD

**Issue by andremarianiello** [dolthub/go-mysql-server#479]
I have a table where I want to index on not just a column, but an expression, e.g.  `JSON_EXTRACT(payload, '$.id')`. The docs for sql.Index say this is allowed

```
    // Expressions returns the indexed expressions. If the result is more than
    // one expression, it means the index has multiple columns indexed. If it's
    // just one, it means it may be an expression or a column.
```

However, it appears that the indexed join transform rule expects these to be only columns

```
// createIndexLookupKeyExpression returns a slice of expressions to be used when evaluating the context row given to the
// RowIter method of an IndexedTableAccess node. Column expressions must match the declared column order of the index.
func createIndexLookupKeyExpression(ctx *sql.Context, ji *joinIndex, tableAliases TableAliases) []sql.Expression {

        keyExprs := make([]sql.Expression, len(ji.index.Expressions()))
IndexExpressions:
        for i, idxExpr := range ji.index.Expressions() {
                for j, col := range ji.cols {
                        if idxExpr == normalizeExpression(ctx, tableAliases, col).String() {
                                keyExprs[i] = ji.comparandExprs[j]
                                continue IndexExpressions
                        }
                }

                // If we finished this loop, we didn't find a column of the index in the join expression.
                // This should be impossible.
                return nil
        }

        return keyExprs
}
```

How can I use an expression index in an indexed join?

**Comment by zachmu** [comment]
This is a defect. Indexes that aren't simple sets of columns are not well tested in the engine, and there are surely lots of places that complex index expressions don't work properly.

Because we're developing this mostly for Dolt, which doesn't yet support complex expressions in indexes, we probably won't get around to making this work for quite some time. We would take a patch if you wanted to try to fix it though.

**Comment by andremarianiello** [comment]
Will do

**Comment by zachmu** [comment]
We'll roll this into https://github.com/dolthub/dolt/issues/2945, please track there.
