### ISSUE TITLE
any performance benchmark for dolt?

### ISSUE THREAD

**Issue by hiqsociety** [dolthub/go-mysql-server#480]
any performance benchmark for dolt?

**Comment by timsehn** [comment]
https://docs.dolthub.com/reference/performance/latency

Goal is 2-4X. We have a change queued that gets write to 8-10X:

https://github.com/dolthub/dolt/pull/1545

**Comment by hiqsociety** [comment]
wow. so disappointing. cant u guys refactor the code? golang shld be only 20% slower than c++

obviously a lot of code is written inefficiently.

**Comment by timsehn** [comment]
MySQL has 25 years of optimizations. We have less than one. Of course we
can make it faster.

But the storage engine is different. It is disk backed and has useful
properties for diffing and merging. So, architecturally, Dolt will not be
as fast for OLTP use cases.

We don't think Go vs C++ has much to do with it.

**Comment by hiqsociety** [comment]
oic. i mean the pure mem area not the git version. in fact i think the git can speed up with rocksdb if it's possible to implement as such

**Comment by timsehn** [comment]
We haven't benchmarked the in memory version. We are in the Dolt business,
not the go-mysql-server business :-)

Most of the optimizations we find are on the storage engine side for Dolt,
but, it wouldn't surprise me if there are a lot of naive implementations in
the in memory version of go-mysql-server.

I'll see if it's easy to run an in memory benchmark and post it in this
issue or tell you it's too hard.

**Comment by zachmu** [comment]
We haven't benchmarked the in-memory implementation, as it's really just for tests.

I would expect the pure reads and writes to be very fast, but anything involving indexes will be as slow as full table scans. The index implementations currently aren't optimized for speed, just for testing correctness of the engine.

We can get benchmarks for the in-memory implementation, but I can't give you an ETA just now.

**Comment by hiqsociety** [comment]
@zachmu thx! looking forward to the pure mem implementation. and also the boilerplate code to write a rocksdb backend with

**Comment by zachmu** [comment]
in-memory benchmarks are being tracked in #514
