### ISSUE TITLE
Anyone working on the replication?

### ISSUE THREAD

**Issue by hiqsociety** [dolthub/go-mysql-server#481]
Pls implement the replication feature of mysql etc.

is there a wal log just curious. if dolt mysql server is down, all data will be lost?

**Comment by timsehn** [comment]
The replication strategy right now is "push on write". You can even have a
background daemon just running push. But yes. It's on our roadmap. See:

https://www.dolthub.com/blog/2021-06-14-dolt-is-a-database/

**Comment by zachmu** [comment]
Dolt replication is now production ready. Nothing native exists in this package, however.
