### ISSUE TITLE
Inserting into UINT32 column can cause error with leading 0

### ISSUE THREAD

**Issue by Hydrocharged** [dolthub/go-mysql-server#498]
Repro:
```sql
CREATE TABLE test (pk BIGINT PRIMARY KEY, v1 INT UNSIGNED);
INSERT INTO test VALUES (1, "04394");
```
Running the above query returns the following error in the integrator https://github.com/dolthub/dolt:
```
INSERT INTO test VALUES (1, "04939"): unable to cast "04939" to uint64: strconv.ParseUint: parsing "04939": invalid syntax
```
This is due to our usage of the `cast` package in https://github.com/dolthub/go-mysql-server/blob/967d6031acbb42745a71f34ae65f590bc81746f7/sql/numbertype.go
We should just remove the `cast` package altogether and rewrite the functionality.

**Comment by Hydrocharged** [comment]
This bug was discovered by: https://github.com/dolthub/dolt/pull/1892

**Comment by zachmu** [comment]
We fixed this at some point.
