### ISSUE TITLE
benchmark memory db

### ISSUE THREAD

**Issue by superdolt** [dolthub/go-mysql-server#514]
any benchmark for this gomysql server in memory compared with mysql?

**Comment by zachmu** [comment]
We don't have this yet, no. But we should.

The dolt backend benchmarks can be found here:

https://docs.dolthub.com/reference/performance/latency

I would expect this to be much faster on some things (table scans) and slower on others, namely anything involving an indexed lookup. The indexed lookups for the in-memory implementation are just suitable for testing the engine correctness and don't provide any speed benefit.
