### ISSUE TITLE
Implement built-in `STR_TO_DATE`

### ISSUE THREAD

**Issue by cmoog** [dolthub/go-mysql-server#518]
Function specification: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_str-to-date

This built-in function offers more flexibility for parsing date values than the existing `DATETIME` function already present in this implementation.

**Comment by zachmu** [comment]
We would take a patch if you wanted to implement this yourself. Not hard, just lots of details to get right and tests needed.

**Comment by cmoog** [comment]
Sounds simple enough. I'll have some time this weekend to knock it out.
