### ISSUE TITLE
Support for generated columns

### ISSUE THREAD

**Issue by knutwannheden** [dolthub/go-mysql-server#561]
MySQL tables can have generated columns (see https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html). When trying to use this feature the statement fails with an error like `[2021-09-22 15:23:19] [HY000][1105] syntax error at position 6229 near 'AS'` or `[2021-09-22 15:23:24] [HY000][1105] syntax error at position 4416 near 'GENERATED'` depending on whether the optional keywords `GENERATED ALWAYS` were specified or not. The MySQL engines may support both virtual and stored generated columns.

**Comment by timsehn** [comment]
We don't support this yet. Zach can scope.

Can you do this with a stored procedure instead?

https://www.dolthub.com/blog/2021-03-10-introducing-stored-procedures/

**Comment by knutwannheden** [comment]
FWIW, generated columns are also supported by MySQL 5.7: https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html

**Comment by timsehn** [comment]
My bad :-)

**Comment by zachmu** [comment]
Closing this in favor of https://github.com/dolthub/dolt/issues/3089, please follow there.
