### ISSUE TITLE
Add support for read-only transactions

### ISSUE THREAD

**Issue by bojanz** [dolthub/go-mysql-server#570]
Running "START TRANSACTION READ ONLY" on latest master gives me:
```
 Error 1105: syntax error at position 23 near 'READ'
```
So I am assuming that read-only transactions are not supported.

Would it make sense to at least swallow the error and treat the transaction as a read-write one?

**Comment by VinaiRachakonda** [comment]
Maybe, in general we want to commands to either error or do what they are supposed to. 

What is your usecase?

**Comment by bojanz** [comment]
Thanks for the reply.

I am trying to use go-mysql-server for integration tests of a Go web app, serving a rest API.
I have a middleware that starts a read-only or read-write transaction for each request, which is then stored in the context for the handlers to use. This is a common pattern, I believe. The read-only transaction is used for GET requests, where a record is loaded from the database and then rendered as JSON.

**Comment by VinaiRachakonda** [comment]
Understood @bojanz.

I talked to the team and it doesn't look super far off to implement. It should be in by early next week.

**Comment by VinaiRachakonda** [comment]
This is merged in to master
