### ISSUE TITLE
_example/main.go unable to compile

### ISSUE THREAD

**Issue by nemccarthy** [dolthub/go-mysql-server#664]
Just testing out the project and it seems the example referred to in the docs doesn't work... 

```
./main.go:69:48: cannot use sql.Schema{...} (type sql.Schema) as type sql.PrimaryKeySchema in argument to memory.NewTable

Compilation finished with exit code 2
```

**Comment by max-hoffman** [comment]
Good catch, we are in the process of refactoring the schema interfaces. This should fix the project example: https://github.com/dolthub/go-mysql-server/pull/668
