### ISSUE TITLE
error: can't modify database databaseProvider

### ISSUE THREAD

**Issue by Rock-liyi** [dolthub/go-mysql-server#705]
I wanna create a database, but it notice me that  can't modify database databaseProvider, so what should i do ?

**Comment by zachmu** [comment]
Can you give some detail on what you're trying to do here? You're trying to use the in-memory database for a test? Trying to create a new backend integration?

**Comment by Rock-liyi** [comment]
> Can you give some detail on what you're trying to do here? You're trying to use the in-memory database for a test? Trying to create a new backend integration?


I already solve this problem,  yes,  i try to use sqlite  to create a new backend integration, it  is a file database.

**Comment by zachmu** [comment]
Glad you figured it out. Let us know if you run into other issues.
