### ISSUE TITLE
Copy the mysql behaviour regarding reserved keywords

### ISSUE THREAD

**Issue by Bios-Marcel** [dolthub/go-mysql-server#750]
I've run into a case where unit tests would run with go-mysql-server, but running against an actual mysql server wouldn't work.
I've got a table called `Option`, which if not escaped in a query, leads to an error in mysql.

These are the currently available keywords:

https://dev.mysql.com/doc/refman/8.0/en/keywords.html

Would you be open to this?

**Comment by zachmu** [comment]
This is difficult to get exactly right, and comes down to differences in the YACC parser we use vs. the one MySQL uses. The MySQL docs are not entirely accurate on this count, e.g. identifiers that are reserved in some statements (CREATE TABLE) work fine in others (INSERT, UPDATE). Some work as table names but fail as column names, etc.

To get closer on this we need to begin with tests that establish a baseline for how MySQL actually behaves for all the keywords listed on the documentation, for all the variations I mention above. Then we can get a list of all the deviations and work on fixing them.

**Comment by Bios-Marcel** [comment]
@timsehn Yes, for now just `Option`

@zachmu I see, understandable. I haven't really looked deep into it yet.

**Comment by zachmu** [comment]
We have made a lot of strides here, enough that I'm going to close this out. If you encounter a keyword difference in parsing that's impacting your use case, please file a bug.
