### ISSUE TITLE
Aggregate Partition Window Rows beyond 127

### ISSUE THREAD

**Issue by inversewd2** [dolthub/go-mysql-server#799]
The number of rows referenced in a partition "ROWS BETWEEN" clause seem to be stored in a short int, because up to and including 127 works, but 128 and above do not.

stocks>  select date, act_symbol, avg(close) OVER (PARTITION BY act_symbol ORDER BY date ROWS BETWEEN 127 PRECEDING AND CURRENT ROW) AS ma200 FROM ohlcv WHERE act_symbol='AAPL' having date = '2022-02-11';
+-------------------------------+------------+--------------------+
| date                          | act_symbol | ma200              |
+-------------------------------+------------+--------------------+
| 2022-02-11 00:00:00 +0000 UTC | AAPL       | 158.39554687499958 |
+-------------------------------+------------+--------------------+

stocks>  select date, act_symbol, avg(close) OVER (PARTITION BY act_symbol ORDER BY date ROWS BETWEEN 128 PRECEDING AND CURRENT ROW) AS ma200 FROM ohlcv WHERE act_symbol='AAPL' having date = '2022-02-11';
*offset must be a non-negative integer; found: 128*

**Comment by max-hoffman** [comment]
@inversewd2 I have spent some time trying to repro without success. The PR you submitted passes our tests, and when i test locally with a table with more than 128 rows I am also getting passing results. I know which error returns the `offset must be a non-negative integer` message, but i can't think of how it is getting triggered at the moment.

If you have any more info on repro-ing i am happy to take a look. If this was a flake and you see it again in the future make sure to ping us again with the error, dolt version, and some same data to repro with. Thanks!

**Comment by inversewd2** [comment]
Hi Max,
Here's an example using Docker python 3.8 base image:


docker run -it --rm python:3.8 bash
root@0ae7f4d0d05e:/# python --version
Python 3.8.12
root@0ae7f4d0d05e:/# bash -c 'curl --retry 10 --retry-delay 2 --retry-all-errors -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134  100   134    0     0     15      0  0:00:08  0:00:08 --:--:--    34
100   649  100   649    0     0     73      0  0:00:08  0:00:08 --:--:--    73
100  3058  100  3058    0     0    249      0  0:00:12  0:00:12 --:--:--  1162
Downloading: https://github.com/dolthub/dolt/releases/download/v0.37.1/dolt-linux-amd64.tar.gz
Installing dolt, git-dolt and git-dolt-smudge to /usr/local/bin.
root@0ae7f4d0d05e:/# dolt version
dolt version 0.37.1
root@0ae7f4d0d05e:/# dolt clone https://doltremoteapi.dolthub.com/post-no-preference/stocks
cloning https://doltremoteapi.dolthub.com/post-no-preference/stocks
101,188 of 101,188 chunks complete. 746,863 chunks being downloaded currently.
root@0ae7f4d0d05e:/# cd stocks
root@0ae7f4d0d05e:/stocks# dolt sql
# Welcome to the DoltSQL shell.
# Statements must be terminated with ';'.
# "exit" or "quit" (or Ctrl-D) to exit.
stocks> select count(*) from ohlcv WHERE act_symbol='AAPL';
+----------+
| count(*) |
+----------+
| 1037     |
+----------+
stocks> select date, act_symbol, avg(close) OVER (PARTITION BY act_symbol ORDER BY date ROWS BETWEEN 128 PRECEDING AND CURRENT ROW) AS ma200 FROM ohlcv WHERE act_symbol='AAPL' having date = '2022-02-11';
offset must be a non-negative integer; found: 128


Also I was able to reproduce the same, using an older project with Dolt 0.36.2.

Thanks,
Adam

**Comment by max-hoffman** [comment]
@inversewd2 Thanks for the more detailed instructions!

I reproduced the error with the stocks database and traced the bug to a fix in this PR:
https://github.com/dolthub/go-mysql-server/compare/max/uint-literal-to-int?expand=1

I am still having a hard time generating a test database that parses 128 as uint8. I'll ask the team and try to figure out what level of the stack is responsible.

**Comment by max-hoffman** [comment]
Ive been told that this is a goyacc issue, there are more parts in the code base where we have to handle the unusual typing for the same reason. Let us know if you run into any similar issues!

**Comment by inversewd2** [comment]
Thanks! Tested successfully with the new trunk.
