### ISSUE TITLE
FilteredTable uses wrong schema with alias

### ISSUE THREAD

**Issue by Allam76** [dolthub/go-mysql-server#808]
When FilteredTable interface is activated on join with table alias, the error  `field <field> is not on schema` shows incorrectly. This only happens with table aliases.

The problem is that the `FixFieldIndexes` uses the alias table schema and not the raw table schema. Therefore the field cannot be found and above error occur.

### To Reproduce

Activate FilteredTable on memory store by setting WithFilters on to Table instead of FilterTable. This activates the implementation. Then run test case `pushdown_filters_to_under_join_node` for example.

Changing from `tableNode.Schema()` to `table.Schema()` in `pushdown.go` did solve the issue for me but unit tests still don't look too encouraging.

**Comment by zachmu** [comment]
If you can get us a test case that demonstrates this bug, we'll get this fixed ASAP.

**Comment by Allam76** [comment]
Test case provided. My apologies for the late reply.

**Comment by fulghum** [comment]
Thanks for reporting this and sending us the awesome test case with the repro @Allam76. That was a big help in debugging. I've got a fix proposed in PR https://github.com/dolthub/go-mysql-server/pull/965

**Comment by Allam76** [comment]
You are welcome :smiley:

**Comment by fulghum** [comment]
Alright, this fix is available on `main` now. 🎉 Thanks again for taking the time to report this and make it easy to debug. Let us know if you hit anything else odd and we'll be happy to dig into it.
