### ISSUE TITLE
Index error lost in parent call

### ISSUE THREAD

**Issue by jfrabaute** [dolthub/go-mysql-server#815]
Hi,

First, thank you for the great package!

I'm not sure if this is intentional, an error reported by a custom index implementation is not handled.
The code is here: https://github.com/dolthub/go-mysql-server/blob/main/sql/analyzer/indexes.go#L71

Should `errInAnalysis = err` be added here (same as the previous if line 61) so the error is reported to the caller?

If so, I can send a PR for the fix.
If not, how should a custom index implementation handle errors that should stop the process?

Thanks.

**Comment by fulghum** [comment]
Thanks for reporting this. Glad to hear you're enjoying the go-mysql-server package! 

Setting `errInAnalysis` to `err` seems to make sense, but I'm tagging @max-hoffman for a more definitive answer, since he's been working with the analyzer index code lately.

**Comment by max-hoffman** [comment]
@jfrabaute Thanks for the catch! @fulghum I'm reading this the same way, I'll fold the fix into a related PR tomorrow morning!

**Comment by jfrabaute** [comment]
I just sent a PR with the fix in case it can help.
Thanks for the quick feedback!

**Comment by jfrabaute** [comment]
(I just realized that with the new index implementation after v0.11 my indices are not merged, so I can't use `latest` anyways. Not sure if the mergeable thing is a regression, I'm trying to have a basic test to reproduce).

**Comment by bpf120** [comment]
@jfrabaute We'd love to hear about how you are using Dolt if you can share. You can email me (brianf@dolthub.com) if that works better than Gitbhub comments or we all hang out on our Discord.

https://discord.com/invite/RFwfYpu

**Comment by max-hoffman** [comment]
@jfrabaute Thank you for the bug report! This was a little more involved than just catching the error, but the next release should include the fix: https://github.com/dolthub/go-mysql-server/pull/824

**Comment by jfrabaute** [comment]
Thanks! I've joined Discord, and I'd be happy to share my use case.
