### ISSUE TITLE
The _example/main.go compile error.

### ISSUE THREAD

**Issue by dongzl** [dolthub/go-mysql-server#888]
I clone the code, and want to run the `_example/main.go`, but this file compile error.

`Cannot resolve file 'auth'`

<img width="757" alt="image" src="https://user-images.githubusercontent.com/5917359/159147543-89553109-aa26-4bdc-b437-f05545b987ad.png">

**Comment by zachmu** [comment]
@JCOR11599 can you fix this quick and add a build rule to make sure that `_example/main.go` builds and runs?

**Comment by fulghum** [comment]
I was actually just checking this out and submitted a PR to remove the referenced auth package from the code sample and the readme: https://github.com/dolthub/go-mysql-server/pull/897

@dongzl  – Thanks for reporting this so we could get this fixed!

**Comment by zachmu** [comment]
Thanks Jason!

**Comment by fulghum** [comment]
This is fixed on main now in the `main.go` file and in the `README` . 

Thanks for checking out `go-mysql-server`. Let us know if you hit any other problems and we'll be happy to help.

**Comment by dongzl** [comment]
Thanks very much!
