### ISSUE TITLE
Does go-mysql-server support create database and table from SQL file?

### ISSUE THREAD

**Issue by dongzl** [dolthub/go-mysql-server#900]
Does go-mysql-server support create database and table from SQL file?

**Comment by zachmu** [comment]
You'll need to write code to feed SQL statements one at a time to the server, this capability is not built in.

Dolt implements this functionality out of the box:

```bash
dolt sql < input.sql
```

You can check out that implementation if you want ideas.

https://github.com/dolthub/dolt/blob/main/go/cmd/dolt/commands/sql.go

**Comment by dongzl** [comment]
Hi @zachmu  Thank you for reply, I will check out it.

**Comment by zachmu** [comment]
Great, closing this out for now.
