### ISSUE TITLE
_example Failure to output

### ISSUE THREAD

**Issue by Penglq** [dolthub/go-mysql-server#911]
I run _example/main.go expected
![image](https://user-images.githubusercontent.com/14035922/160051992-7b11aaa9-7929-41d5-be21-05c4b0e67851.png)
but got
![image](https://user-images.githubusercontent.com/14035922/160052031-19d0e97e-43f1-4055-8890-1f06a34024c2.png)

jsonType and timestamp output is wrong

**Comment by zachmu** [comment]
This points to an incompatibility in returning JSON objects over the wire for in memory tables.

James, can you please take a look at what's going on here?

**Comment by fulghum** [comment]
Big thanks for reporting this problem @Penglq. @JCOR11599 got the fix into main and it'll go out in our next release this week. Let us know if you hit any more issues with go-mysql-server and we'll be happy to jump on them.
