### ISSUE TITLE
willing to maintaion sql standard schema support?

### ISSUE THREAD

**Issue by Allam76** [dolthub/go-mysql-server#989]
I'm working on a federated sql tool based on go-mysql-server. Think smaller version of apache calcite or presto. In this use case I need to handle the sql standard schema concept, which is a namespace in the database. This is implemented in many sql databases such as postgres, mssql, oracle, etc but not in mysql. Alas in go-mysql-server it does not exist.

The "proper" solution to handle this would be to either introduce a "schema" namespace object or change the table key from simple ```string``` to composite key ```[2]string```.

However, this would require a refactoring of a large part of the code base. I could do the actual work but would you be willing to maintain such a large change that has only added value for the community and no added value for dolt?

For info, I could also use a workaround and create a composite key as string and do the splitting in my extension. But it seems less optional.

**Comment by zachmu** [comment]
Hi @Allam76 ,

As you point out, MySQL doesn't support schemas within a database. We're not looking to add such a feature at the moment.

You can put `.` characters in your table names, but then you'll need to quote them in most SQL statements, e.g.:

```sql
select * from `my.table`
```
